/* tslint:disable */
/* eslint-disable */
/*
Visier Consolidated Analytics APIs

Visier APIs for managing consolidated analytics (CA) tenants.

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/


export * from './api/consolidated-analytics-v1-alpha-api';

