/*
Visier Consolidated Analytics APIs

Visier APIs for managing consolidated analytics (CA) tenants.

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  ConsolidatedAnalyticsV1AlphaApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { VisierConsolidatedAnalyticsCustom } from "./client-custom";

export class VisierConsolidatedAnalytics extends VisierConsolidatedAnalyticsCustom {
  readonly consolidatedAnalyticsV1Alpha: ConsolidatedAnalyticsV1AlphaApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.consolidatedAnalyticsV1Alpha = new ConsolidatedAnalyticsV1AlphaApi(configuration);
  }

}
