/*
Visier Consolidated Analytics APIs

Visier APIs for managing consolidated analytics (CA) tenants.

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConsolidatedAnalyticsAPISourceTenantListDTO
 */
export interface ConsolidatedAnalyticsAPISourceTenantListDTO {
    /**
     * A list of a CA tenant\'s source tenants codes
     * @type {Array<string>}
     * @memberof ConsolidatedAnalyticsAPISourceTenantListDTO
     */
    'tenantCodes'?: Array<string>;
}

