/*
Visier Consolidated Analytics APIs

Visier APIs for managing consolidated analytics (CA) tenants.

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface ConsolidatedAnalyticsAPITenantCreateRequestDTO
 */
export interface ConsolidatedAnalyticsAPITenantCreateRequestDTO {
    /**
     * The ID of the tenant. For example, WFF_{XXX}~CA{YYY} where {XXX} is the administrating tenant code and {YYY}  is the consolidated analytic tenant code.
     * @type {string}
     * @memberof ConsolidatedAnalyticsAPITenantCreateRequestDTO
     */
    'tenantCode'?: string;
}

