/*
Visier Consolidated Analytics APIs

Visier APIs for managing consolidated analytics (CA) tenants.

The version of the OpenAPI document: 22222222.99201.1200


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * 
 * @export
 * @interface TenantCodeBody
 */
export interface TenantCodeBody {
    /**
     * A list of a CA tenant\'s source tenants codes. The maximum length is 1000.
     * @type {Array<string>}
     * @memberof TenantCodeBody
     */
    'tenantCodes'?: Array<string>;
}

